headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\SARATH CHANDRAN R\\zeus-salon"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/frames/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/css/*"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/js/*"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"